import type { Preview } from '@storybook/react';

// Import compiled Arco tokens — generated by `npm run build`
import '../../../dist/css/arco.css';

const preview: Preview = {
  parameters: {
    backgrounds: {
      default: 'light',
      values: [
        { name: 'light', value: '#ffffff' },
        { name: 'dark', value: '#17171a' },
      ],
    },
    // Enable dark theme via data-theme attribute
    globalTypes: {
      theme: {
        name: 'Theme',
        defaultValue: 'light',
        toolbar: {
          icon: 'circlehollow',
          items: ['light', 'dark'],
          showName: true,
        },
      },
    },
  },
  decorators: [
    (Story, context) => {
      const theme = context.globals?.theme ?? 'light';
      document.documentElement.setAttribute('data-theme', theme);
      return Story();
    },
  ],
};

export default preview;
